name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    env:
      PORT: 80
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done - bye!"
      - name: multi-line
        run: |
          echo "hello DevOps Guys"
          echo "${{ env.PORT }}"